### ISSUE TITLE
Shell Script case statement indentation

### ISSUE THREAD

**Issue by MithrilTuxedo** [textmate/shellscript.tmbundle#24]
Currently the shell script formatter tries formatting case statements like this:

``` bash
case $value in
    pattern1)
    statement1A
    statement1B
    ;;
    pattern2)
    statement2A
    statement2B
    ;;
esac
```

What I'm more familiar with, and all references I can find comport with this, is this which is more like switch formatting in other languages:

``` bash
case $value in
    pattern1)
        statement1A
        statement1B
        ;;
    pattern2)
        statement2A
        statement2B
        ;;
esac
```

I'm not familiar enough with how the formatting system works in TextMate to know if this works universally, but I've edited my Shell Script > Settings > Miscellaneous bundle in a way that seems to work.

My changes are in fixed-width:

> { increaseIndentPattern = '^\s*(if|then|elif|else|case)\b|^.*(\{|\b(do)\b)$`|^((?!\().)\*\)$`';
>   decreaseIndentPattern = '^\s*(\}|(then|elif|else|fi|esac|done`|;;`)\b)';
>   indentNextLinePattern = '^.*[^\\]\\$';
> }

The intent is to increase the indent after a line ending in `)` and not otherwise containing `(`, then decrease indent after `;;`.

**Comment by MithrilTuxedo** [comment]
Actually, that doesn't even work well.

Using decreaseIndentPattern = '^\s\*(\\}|(then|elif|else|fi|esac|done)\b)`|.\*;;$`' works a little better giving:

```bash
case $value in
    pattern1)
        statement1A
        statement1B
    ;;
    pattern2)
        statement2A
        statement2B
    ;;
esac
```

**Comment by mkhl** [comment]
Thanks for trying this, and sorry it took me so long to respond.

The reason I hadn't tried to change indentation here is that the patterns may actually start with an optional `(` character, which makes them impossible to distinguish from subshells.
Also, as you noticed, the common patterns don't map well to what TextMate supports.

What do you think we should do?

For reference, the common indentation patterns I'm aware of are

    case $value in
        pattern)
            command
            ;;
    esac

and

    case $value in
    pattern)
        command
        ;;
    esac

(A rarer short form is `pattern) command ;;` on a single line.)

I prefer the second form, and have settled on letting TextMate indent as it would now, then shifting the patterns to the left.

**Comment by ThePantsThief** [comment]
Wouldn't you rather it at least indent one of them and fix it for the rare case you're not trying to do that?

**Comment by mkhl** [comment]
I found a configuration that matches the style of the `case` snippet. It works by adding the case pattern to both `increaseIndentPattern` and `decreaseIndentPattern`:

```
{	increaseIndentPattern = '^\s*(if|then|elif|else|case)\b|^.*(\{|\b(do)\b)$|^\s*[^(]*\)$';
	decreaseIndentPattern = '^\s*(\}|(then|elif|else|fi|esac|done)\b)|^\s*[^(]*\)$';
	indentNextLinePattern = '^.*[^\\]\\$';
}
```

> And shouldn't `indentNextLinePattern` be `^.*[^\\]\\$` instead of `^.*[^\]\$`?

Yes it should.

**Comment by mkhl** [comment]
If you prefer this style:

```bash
case $value in
    pattern)
        command
        ;;
esac
```

You can adapt the “case…esac” snippet to match and the new indentation rules will support it, only the “Indent Selection” command will enforce the default style.
