### ISSUE TITLE
Failure running script "Run Script"

### ISSUE THREAD

**Issue by caiwenhn2008** [textmate/shellscript.tmbundle#27]
HI, there is an issue by running cmd+R on Textmate2

error log: 
No web preview theme found.
Make sure that the Themes bundle is enabled in Preferences->Bundles

actually, i installed all the theme in the bundle list.

**Comment by sorbits** [comment]
See https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by sorbits** [comment]
Closing due to lack of follow-up and presumably a local problem.
