### ISSUE TITLE
iTerm2 not being detected when using "Open Terminal" menu

### ISSUE THREAD

**Issue by meneguzzi** [textmate/shellscript.tmbundle#28]
For a couple of weeks now, whenever I use the Open Terminal menu command (ctrl+shift+O) TextMate opens its default terminal rather than iTerm2 (this did not happen before). This happens even if I set the environment variable "TM_TERMINAL"  to the full path to iTerm2 (so the neither parts of the or condition in the ruby code are being triggered). I feel this may be related to the recent upgrade to iTerm2, since I only noticed this after iTerm2 has been released,

**Comment by sorbits** [comment]
Some info here about what to do to support both versions if iTerm2 (as 
they did make changes to the AppleScript syntax): 
https://www.iterm2.com/applescript.html

**Comment by meneguzzi** [comment]
Thanks for the quick reply and my apologies for my delay in responding.
So, should I just go to the Bundle editor and replace the code for the open terminal menu? If the code supports both versions of iTerm2, why not update the bundle in Github then?

**Comment by infininight** [comment]
@meneguzzi Yes is should be fixed here, @sorbits was adding a note to the issue as more information on how the problem can be corrected. This will be corrected as time permits, if a someone else corrects this a pull request can be made to speed along the process.

**Comment by meneguzzi** [comment]
Got it, if I get time to try out and test the changes I will create a pull request. Thanks for the responsiveness.

**Comment by meneguzzi** [comment]
I just could not avoid obsessing over getting this to work, so I just did a pull request with the updated code. Let me just add that I am not very proficient with branching and pull requests in Git (sorry I'm an SVN generation person) nor am I terribly proficient with Applescript (but that looked simple enough). I did testing locally and hope this will address somebody's immediate need.

I hope this helps.

**Comment by mkhl** [comment]
LGTM, assuming we can/want to drop support for the old iTerm
(which I think everyone should have switched away from by now).

Thank you @meneguzzi!

**Comment by meneguzzi** [comment]
The link @sorbits gave also have some code to support both, but I think the procedure will get very unwieldy.
As you say, perhaps its time to move on to iTerm2. There's no reason not to.

**Comment by infininight** [comment]
Not sure what the breakdown in usage is for the iTerm versions or how stable the 2.9 beta release is considered to be. Might be a bit soon to cutoff support for 2.1 as 2.9 has only been available for less than a month.

**Comment by mkhl** [comment]
Oh, my bad. I misread and thought this would support any iTerm2 release, not just the 2.9 series.

**Comment by meneguzzi** [comment]
If I get more time this week I will try to add support for the older versions (there's an explanation there on how to). Having said that, can anyone with an earlier version of iTerm download the code and test it?

**Comment by sorbits** [comment]
I merged the PR but preserved the old version of the script, this will be used when `TM_TERMINAL` is unset and an `iterm` process is running (I did not test that the previous version of iTerm2 actually has a process name of `iTerm`, though this is the name of its AppleScript port).

Thanks for the work on this @meneguzzi and sorry about the delay in merging, had mentally assigned it to @mkhl 😀

**Comment by meneguzzi** [comment]
No worries, I'm glad I could contribute (and learn something about Apple script in the process).
