### ISSUE TITLE
Shell script syntax highlighting stops after several one line function declarations

### ISSUE THREAD

**Issue by aeschli** [textmate/shellscript.tmbundle#31]
_From @Alexendoo on August 14, 2016 15:54_

- VSCode Version: 1.4.0
- OS Version: Windows 8.1

Moving the final bracket down one line seems to fix it, moving the first bracket seems to change the effect by one. It doesn't seem that the depth of the declaration has any effect.

Jumping to the matching bracket still seems to function as expected

![image](https://cloud.githubusercontent.com/assets/1830331/17650171/deaa7a14-623e-11e6-8f87-bc502a4fa4f3.png)

_Copied from original issue: Microsoft/vscode#10521_

**Comment by aeschli** [comment]
The problem is that the grammar begins the "meta.scope.group.shell" rule, but doesn't leave it.
The rule that consumes 'echo ":(" also matches the closing bracket.

**Comment by mkhl** [comment]
The above are **not** valid function definitions according to bash(1), see the section “Compound Commands” in the man page.

The list of commands (emphasis mine):

> **must** be  terminated with a newline or semicolon.

Add the missing terminator and `meta.scope.group.shell` is closed correctly and the closing brace is marked as `punctuation.definition.group.shell`.

**Comment by aeschli** [comment]
Thanks @mkhl .
@Alexendoo FYI
