### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by revolter** [textmate/shellscript.tmbundle#37]
[This file][1] has incorrect syntax highlighting after this line:

    defaults write com.apple.Safari ProxiesInBookmarksBar "()"

  [1]: https://github.com/mathiasbynens/dotfiles/blob/dd808d5d50912afbb9c78d359a8e4f773621f769/.macos#L488

**Comment by mkhl** [comment]
I don’t see any problem with it. Do you mean in the GitHub web UI?

**Comment by revolter** [comment]
Yes, on the GitHub website. As far as I understood, it uses this organization's repositories' syntax files, right?

**Comment by mkhl** [comment]
I think that *used* to be true but isn’t. You want https://github.com/github/linguist.
