### ISSUE TITLE
Shell script coloration issue

### ISSUE THREAD

**Issue by aeschli** [textmate/shellscript.tmbundle#39]
_From @sthonnard on August 7, 2017 14:24_

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Create a new Shell Script

2. Write the following:
```
PUT_FILES=$( ls -1 *$RUN_DATE* | while read a; do echo "put $a"; done) 
GET_FILES=$( ls -1 *$RUN_DATE* | while read a; do echo "get $a"; done) 
```

_Copied from original issue: Microsoft/vscode#32089_

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/29923932-71930c94-8e5b-11e7-8640-10dd1e167e8a.png)

**Comment by mkhl** [comment]
Thanks for the report and reproduction
