### ISSUE TITLE
fails to parse string with parentheses "()"

### ISSUE THREAD

**Issue by jtmoon79** [textmate/shellscript.tmbundle#43]
The following shell script does not terminate the string token on line 2.

     #!/bin/bash
     echo "()"
     echo bar

Line 3, `echo bar`, is errantly colored as a continuation of the string `"()"` on line 2.

Seen in [atom.io](https://github.com/atom/atom) version _1.17.2 x64_ using package _[language-shellscript](https://github.com/atom/language-shellscript) 0.25.0_.

**Comment by mkhl** [comment]
Doesn’t seem to apply to this
